//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CharacterManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CharacterManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;PlayerRace&gt;
        ///    &lt;RaceName&gt;Dwarf&lt;/RaceName&gt;
        ///    &lt;BonusAttributes&gt;
        ///      &lt;STR&gt;0&lt;/STR&gt;
        ///      &lt;DEX&gt;0&lt;/DEX&gt;
        ///      &lt;INT&gt;0&lt;/INT&gt;
        ///      &lt;CHA&gt;0&lt;/CHA&gt;
        ///      &lt;CON&gt;2&lt;/CON&gt;
        ///      &lt;WIS&gt;0&lt;/WIS&gt;
        ///    &lt;/BonusAttributes&gt;
        ///    &lt;NumberOfGenericBonusAttributes&gt;0&lt;/NumberOfGenericBonusAttributes&gt;
        ///	&lt;WeaponProficiencies&gt;
        ///		&lt;string&gt;battleaxe&lt;/string&gt;
        ///		&lt;string&gt;handaxe&lt;/string&gt;
        ///		&lt;string&gt;throwing hammer&lt;/string&gt;
        ///		&lt;string&gt;warhammer&lt;/string&gt;
        ///	&lt;/WeaponProficiencies&gt;
        ///	&lt;MaximumAge&gt;350&lt;/MaximumAge&gt;
        ///	&lt;Size&gt;Medium&lt;/Size&gt;
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Dwarf {
            get {
                return ResourceManager.GetString("Dwarf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;PlayerRace&gt;
        ///    &lt;RaceName&gt;Elf&lt;/RaceName&gt;
        ///    &lt;BonusAttributes&gt;
        ///      &lt;STR&gt;0&lt;/STR&gt;
        ///      &lt;DEX&gt;2&lt;/DEX&gt;
        ///      &lt;INT&gt;0&lt;/INT&gt;
        ///      &lt;CHA&gt;0&lt;/CHA&gt;
        ///      &lt;CON&gt;0&lt;/CON&gt;
        ///      &lt;WIS&gt;0&lt;/WIS&gt;
        ///    &lt;/BonusAttributes&gt;
        ///    &lt;NumberOfGenericBonusAttributes&gt;0&lt;/NumberOfGenericBonusAttributes&gt;
        ///	&lt;MaximumAge&gt;750&lt;/MaximumAge&gt;
        ///	&lt;Size&gt;Medium&lt;/Size&gt;
        ///	&lt;BaseSpeed&gt;30&lt;/BaseSpeed&gt;
        ///	&lt;SkillProficiencies&gt;
        ///		&lt;string&gt;Perception&lt;/string&gt;
        ///	&lt;/SkillProficiencies&gt;
        ///	&lt;PlayerAttributes&gt;
        ///		&lt;string&gt;Darkvision&lt;/string&gt;
        ///		&lt;string&gt;Fey Ance [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Elf {
            get {
                return ResourceManager.GetString("Elf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;PlayerClass&gt;
        ///	&lt;PlayerClassName&gt;Fighter&lt;/PlayerClassName&gt;
        ///	&lt;HitDie&gt;10&lt;/HitDie&gt;
        ///	&lt;WeaponProficiencies&gt;
        ///		&lt;string&gt;Martial Weapons&lt;/string&gt;
        ///		&lt;string&gt;Simple Weapons&lt;/string&gt;
        ///	&lt;/WeaponProficiencies&gt;
        ///	&lt;ArmorProficiencies&gt;
        ///		&lt;string&gt;Light Armor&lt;/string&gt;
        ///		&lt;string&gt;Medium Armor&lt;/string&gt;
        ///		&lt;string&gt;Heavy Armor&lt;/string&gt;
        ///		&lt;string&gt;Shields&lt;/string&gt;
        ///	&lt;/ArmorProficiencies&gt;
        ///	&lt;SavingThrowProficiencies&gt;
        ///		&lt;string&gt;STR&lt;/string&gt;
        ///		&lt;string&gt;CON&lt;/string&gt;
        ///	&lt;/SavingThrowProficiencies&gt;
        ///	&lt;AvailableSkillProficiencies&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Fighter {
            get {
                return ResourceManager.GetString("Fighter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;PlayerRace&gt;
        ///&lt;RaceName&gt;Human&lt;/RaceName&gt;
        ///	&lt;BonusAttributes&gt;
        ///		&lt;STR&gt;1&lt;/STR&gt;
        ///		&lt;DEX&gt;1&lt;/DEX&gt;
        ///		&lt;INT&gt;1&lt;/INT&gt;
        ///		&lt;CHA&gt;1&lt;/CHA&gt;
        ///		&lt;CON&gt;1&lt;/CON&gt;
        ///		&lt;WIS&gt;1&lt;/WIS&gt;
        ///    &lt;/BonusAttributes&gt;
        ///	&lt;NumberOfGenericBonusAttributes&gt;0&lt;/NumberOfGenericBonusAttributes&gt;
        ///&lt;/PlayerRace&gt;.
        /// </summary>
        internal static string Human {
            get {
                return ResourceManager.GetString("Human", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap old_paper_texture {
            get {
                object obj = ResourceManager.GetObject("old-paper-texture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;PlayerClass&gt;
        ///	&lt;PlayerClassName&gt;Wizard&lt;/PlayerClassName&gt;
        ///	&lt;HitDie&gt;6&lt;/HitDie&gt;
        ///	&lt;WeaponProficiencies&gt;
        ///		&lt;string&gt;Daggers&lt;/string&gt;
        ///		&lt;string&gt;Darts&lt;/string&gt;
        ///		&lt;string&gt;Slings&lt;/string&gt;
        ///		&lt;string&gt;Quarterstaffs&lt;/string&gt;
        ///		&lt;string&gt;Light Crossbows&lt;/string&gt;
        ///	&lt;/WeaponProficiencies&gt;
        ///	&lt;ArmorProficiencies&gt;
        ///	&lt;/ArmorProficiencies&gt;
        ///	&lt;SavingThrowProficiencies&gt;
        ///		&lt;string&gt;INT&lt;/string&gt;
        ///		&lt;string&gt;WIS&lt;/string&gt;
        ///	&lt;/SavingThrowProficiencies&gt;
        ///	&lt;NumberOfSkillsToChoose&gt;2&lt;/NumberOfSkillsToChoose&gt;
        ///	&lt;AvailableSkillProficien [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Wizard {
            get {
                return ResourceManager.GetString("Wizard", resourceCulture);
            }
        }
    }
}
